name: validate
on:
  - push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        run: sudo apt-get install -y autoconf automake cmake gcc libtool libssl-dev make ninja-build zlib1g-dev
      -
        name: fetch openssh repo
        uses: actions/checkout@v4
      -
        name: fetch liboqs repo
        run: ./oqs-scripts/clone_liboqs.sh
      -
        name: build liboqs
        run: ./oqs-scripts/build_liboqs.sh
      -
        name: ssh environment
        run: |
          sudo mkdir -p -m 0755 /var/empty
          sudo groupadd sshd
          id sshd || sudo c -g sshd -c 'sshd privsep' -d /var/empty -s /bin/false sshd
      -
        name: build openssh
        env:
          INSTALL_PREFIX: ${{ github.workspace }}/oqs-test/tmp
          WITH_OPENSSL: true
        run: ./oqs-scripts/build_openssh.sh
      -
        name: log build artifacts
        run: ls -ahl ${{ github.workspace }}/oqs-test/tmp
      -
        name: upload oqs-openssh
        uses: actions/upload-artifact@v4
        with:
          name: oqs-openssh
          path: ${{ github.workspace }}/oqs-test/tmp
      -
        name: upload build-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ github.workspace }}/Makefile
            ${{ github.workspace }}/openbsd-compat/Makefile
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: fetch openssh repo
        uses: actions/checkout@v4
      -
        name: download oqs-openssh
        uses: actions/download-artifact@v4
        with:
          name: oqs-openssh
          path: ${{ github.workspace }}/oqs-test/tmp
      -
        name: download build-artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ${{ github.workspace }}
      -
        name: log build artifacts
        run: ls -ahl ${{ github.workspace }}/oqs-test/tmp
      -
        name: test
        run: ${{ github.workspace }}/oqs-test/run_tests.sh
      -
        name: validate algorithms
        run: >
          python3 oqs-test/try_connection.py
            --ssh ${{ github.workspace }}/oqs-test/tmp/bin/ssh
            --sshd ${{ github.workspace }}/oqs-test/tmp/sbin/sshd
            doone
